alias sn='sudo nano'
alias ag='sudo apt-get'
alias diskusage='sudo du -sh * | sort -hf'
alias svim='sudo vim'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias gitpta 'git remote | xargs -L1 git push --all'
