#!/bin/bash

connectionName='cmgraylogProxy'

down='<span foreground="#FF0000"></span>'
up='<span foreground="#00FF00"></span>'
state="$(ssh -O check cmgraylogProxy 2>&1)"
notification=""

if [[ $state == *"Master running"* ]]; then
    echo "$up"
    rightclick="pkill -RTMIN+4 i3blocks && ssh -O exit $connectionName"
    notification="kill proxy connection"
else
    echo "$down"
    rightclick="pkill -RTMIN+4 i3blocks && ssh -fN $connectionName"
    notification="start proxy connection"
fi


case $BLOCK_BUTTON in
    3) notify-send "$notification" && $rightclick;;
    *) ;;
esac
