#!/bin/bash

function toggleVpn() {
    vpn="TUD"
    state="$(~/.config/i3blocks/scripts/netCheck vpn0)"
    if [ "$state" == "1" ]
    then
        notify-send "disable $vpn"
        nmcli con down id $vpn >> /dev/null
    else
        notify-send "enable $vpn"
        nmcli con up id $vpn >> /dev/null
    fi
}
function showStatus() {
    state="$(~/.config/i3blocks/scripts/netCheck vpn0)"
    down='<span foreground="#FF0000"></span>'
    up='<span foreground="#00FF00"></span>'
    
    if [ "$state" == '1' ]
    then
        echo "$up"
    else
        echo "$down"
    fi
}
case $BLOCK_BUTTON in
    3) toggleVpn ; showStatus;;
    *) showStatus;;
esac

