#!/bin/bash
file="$1"
sec=0
color="#FF8000" #orange
red="#FF0000" #red

function timerizeNumber() {
    if [[ "$1" -lt 10 ]] ; then
        return="0$1"
    else
        return="$1"
    fi
}
if ! [ -f "$file" ]; then
    echo "$file does not exist"
    exit 1
fi

while IFS= read -r line; do
    re='^[0-9]+$'
    if ! [[ $line =~ $re ]] ; then
       echo "error: Not a sec" >&2;
       exit 1
    else
        sec=$line
    fi
done < "$file"


if [[ "$sec" -lt 10 ]] ; then
        color=$red
fi

if [[ "$sec" -eq 0 ]] ; then
    #send notification and delete file
    notify-send "################### time end ##################" --urgency=critical
    rm "$file"
else
    #write filecontent-1 back to file
    out=$((sec-1))
    echo "$out" > "$file"
fi

#convert seconds to hours, minutes, and seconds
hours=$((sec/3600))
sec=$((sec-hours*3600))
min=$((sec/60))
sec=$((sec-min*60))

#add a leading 0 if its a single digit
timerizeNumber $hours
hours=$return
timerizeNumber $min
min=$return
timerizeNumber $sec
sec=$return

#print
OUT='<span foreground="'
OUT+="$color"
OUT+='">'
OUT+="${hours}:${min}:${sec}"
OUT+="</span>"
echo $OUT
