#!/bin/bash
if [ "$#" != 0 ]
then
    string="$(/usr/bin/ip link)"
    if [[ "$string" == *"$1"* ]]
    then
        string="$(/usr/bin/ip link | grep "$1")"
        if [[ "$string" == *"UP"* ]]
        then
            #UP
            echo '1'
        else
            #DOWN
            echo '0'
        fi
    else
        #DOWN
        echo '0'
    fi
fi
